# Generated by Django 5.0.3 on 2024-06-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to='images/'),
        ),
    ]
