# Generated by Django 5.0.3 on 2024-06-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='https://example.com/path/to/default/image.jpg', upload_to='images/'),
        ),
    ]
